[package]
name = "deckport-vpn-desktop"
version = "0.2.6"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
eframe = { version = "=0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
libc = "0.2"
serde_json = "1.0"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"
